server:
  port: 8889
  servlet:
    context-path: /canal-kafka
spring:
  kafka:
    bootstrap-servers: 192.168.16.129:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: canal-kafka-demo
      # commit
      enable-auto-commit: false
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 60000
    listener:
      log-container-config: false
      concurrency: 5
      # commit
      ack-mode: manual_immediate

hostAndPort: 192.168.16.129:9200