spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        min-idle: 0
  datasource:
      url: jdbc:mysql://localhost:3306/my_learn
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cache:
    type: redis
    redis:
      time-to-live: 10000
      cache-null-values: false
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: caihaoyun@smartbi.com.cn
    password: Chy19931018
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true