spring:
  datasource:
      url: jdbc:mysql://localhost:3306/my_learn
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
